# -*- coding: utf-8 -*-
"""Wei Lang Chan -  Project_2_Binary_Classifications_wbdc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaTyqfZKN7d-EaNsny1GwBgWBhrPeSzh

Binary Classification

## Wisconsin Diagnostic Breast Cancer (WDBC) - Attribute information

1.  ID number
2.  Diagnosis (M = malignant, B = benign)

3-32: Ten real-valued features are computed for each cell nucleus:

	a) radius (mean of distances from center to points on the perimeter)
	b) texture (standard deviation of gray-scale values)
	c) perimeter
	d) area
	e) smoothness (local variation in radius lengths)
	f) compactness (perimeter^2 / area - 1.0)
	g) concavity (severity of concave portions of the contour)
	h) concave points (number of concave portions of the contour)
	i) symmetry
	j) fractal dimension ("coastline approximation" - 1)

Several of the papers listed above contain detailed descriptions of
how these features are computed.

The mean, standard error, and "worst" or largest (mean of the three
largest values) of these features were computed for each image,
resulting in 30 features.  For instance, field 3 is Mean Radius, field
13 is Radius SE, field 23 is Worst Radius.

All feature values are recoded with four significant digits.

8. Missing Attribute Values: None

9. Class distribution: 357 benign, 212 malignant
"""

# Importing files and libraries.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score


from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn import metrics
from sklearn.metrics import confusion_matrix

"""In this notebook, we are using an anonymized dataset of students with accommodations from July 2025 to March 2026 who have submitted an exam request for accommodated exams to determine and explore independent variables that may predict our dependent variable (service demand of proctoring services). After completing an Exploratory Data Analysis (EDA)...."""

# Importing CSV datasets for Google Drive and creating data frame

from google.colab import drive
drive.mount('/content/drive')
file_path_1 = '/content/drive/My Drive/Datasets/Project_2/data.csv'


df = pd.read_csv(file_path_1) # Reading Wisconsin Diagnostic Breast Cancer (WDBC) and creating dataframe.

pd.set_option('display.max_columns', None)
df.head(10) # displaying first 10 rows

df.isnull().sum() # Checking missing values.

df.columns.to_list() # Reviewing data points by pulling a list of column headers.

df.info(verbose=True, show_counts=True) #  Forces the full summary to be displayed and non-null counts for every column.

df['id'].duplicated().sum() # Validating there is no duplicated data.

# Mapping diagnosis (M = malignant, B = benign) to 1 = malignant and 0 = benign for binary classification.
df['diagnosis'] = df['diagnosis'].map({'M':1,'B':0})
df.head() # Displaying first 5 rows after mapping

"""The dataset provides 32 different data points. Given that there is no duplicate data, the 'id' column and column 32 (unnamed) will be removed from the dataframe."""

# Removing 'id' and 'Unnamed: 32' columns to clean and prepare the data.
df.drop('id',axis=1,inplace=True)
df.drop('Unnamed: 32',axis=1,inplace=True)

df.head() # Validating changes to columns in the DataFrame.

"""# Exploratory Data Analysis (EDA)
For the Exploratory Data Analysis, I will use a histogram to better understand any apparent visual patterns and relations between each feature (attribute) with the diagnosis. This will be completed through overlapping grouped bar charts. The grouped bar chart will compare the diagnosis along with the features values and visualize if the count of a diagnosis may have a relationship with the feature presences. The heatmap may also present a correlation between features and it's coorelation with a malignant diagnosis. By having the two plots, we can validate the coorelation seen and complete the binary classification on the observed significant features.
"""

#  Categorical Features vs. Target. Visualizing features against diagnosis.

fig = plt.figure(figsize=(24, 50)) # Increased figure height for more rows

# Retrieving feature columns except for diagnosis.
feature_columns = df.columns[1:]
feature_count = len(feature_columns) # Total amount of feature columns identified.
cols = 3 # Number of columns in the subplot grid
rows = 10 # Number of rows in the subplot grid

# Retrieving numeric value and column name through loop function.
# Loop subfigures for individual subplot specific to the position and stacks diagnosis histogram on top of each feature graph.
for i, column in enumerate(feature_columns):
  subfigure = fig.add_subplot(rows, cols, i + 1)
  subfigure.set_xlabel(column)
  sns.histplot(data=df, x=column, hue='diagnosis', multiple='stack', palette={1: 'red', 0: 'orange'}, ax=subfigure, alpha=0.2) # Stacked for visual comparison and transparency
  subfigure.legend(labels=['Malignant', 'Benign'], title='Diagnosis')
plt.tight_layout()
plt.show() # Display the histogram

"""## Interpretation
Large mean values observed in radius, perimeter, area, compactness, concavity and concave data points may demonstrate higher correlation to malignant diagnosis and should be used in binary classification. This is demonstrated in the mean and worst features, with features in "se" displaying left skewness with some values present in the higher ranges.
No significant outliers visualized.
"""

# Grouping 3 groups of "mean", "se", and "worst" for further review.
df_mean= df[df.columns[0:10]]
df_se= df[df.columns[10:20]]
df_worst = df[df.columns[20:30]]

# Visualization of Dataframe with heatmaps grouped by Mean, SE, and Worst.

plt.figure(figsize=(10, 30)) # Adjust figure size for vertical layout

plt.subplot(3, 1, 1) # Organizing location for Mean Features Heatmap
sns.heatmap( df_mean.corr(), cbar = False,  square = True, annot=True, fmt= '.2f',annot_kws={'size': 8},cmap= 'Reds', linewidths= 1)
plt.title('Correlation Heatmap - Mean Features')

plt.subplot(3, 1, 2) # Organizing location for Worst Features Heatmap
sns.heatmap(df_worst.corr(), cbar = False,  square = True, annot=True, fmt= '.2f',annot_kws={'size': 8},cmap= 'Reds', linewidths= 1)
plt.title('Correlation Heatmap - Worst Features')

plt.subplot(3, 1, 3) # Organizing location for SE Features Heatmap
sns.heatmap(df_se.corr(), cbar = True,  square = True, annot=True, fmt= '.2f',annot_kws={'size': 8},cmap= 'Reds', linewidths= 1)
plt.title('Correlation Heatmap - SE Features')

plt.tight_layout() # Adjust layout to prevent overlapping
plt.show()

"""## Interpretation:

Heatmap shows similar results with malignant diagnosis correlating with radius, perimeter, area, compactness, and concave features, and validates initial grouped bar chart interpretations.

# Split Dataset into Training and Testing Set

I will be splitting the data into an simple 80:20 split of the unordered dataframe to create a supervised learning model. A Logistic Regression model will be used.

The Logistic Regression model is used due to the likelihood that the relationship between features and the target is approximately linear as a 2-class problem (malignant or benign). If the presence of a particular combination of features is found, the model can find the best-fit decision boundary.
"""

y = df['diagnosis'] # Defining y-axis
x = df[['radius_mean','perimeter_mean','area_mean','compactness_mean','concave points_mean']] # Defining x-axis with features highlights in visuals.
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state=42) # 20% of data will be used to test model.

print(f"Training data shape: X={X_train.shape}, Y={y_train.shape}")
print(f"Test data shape: X={X_test.shape}, Y={y_test.shape}")

"""# Logistic Regression:"""

lr_model = LogisticRegression() # liblinear is best suited for small datasets.
lr_model.fit(X_train, y_train) # Training the model
y_pred_lr = lr_model.predict(X_test) # Making predictions on the test set

# Displaying performance metrics
print('Logistic Regression Model Performance:')
print('Precision:', precision_score(y_test, y_pred_lr))
print('Accuracy:', accuracy_score(y_test, y_pred_lr))
print('Recall:', recall_score(y_test, y_pred_lr))
print('F1-Score:', f1_score(y_test, y_pred_lr))
print('AUC', metrics.roc_auc_score(y_test, y_pred_lr))
print('Confusion Matrix:', confusion_matrix(y_test, y_pred_lr))

# Confusion metric
fig = plt.figure(figsize=(10, 8))

cm_lr = confusion_matrix(y_test, y_pred_lr)
cm_plot=sns.heatmap(cm_lr, annot=True, cmap = 'Blues_r')
cm_plot.set_title('WDBC Logistic Regression Confusion Matrix')
cm_plot.set_xlabel('Predicted Values')
cm_plot.set_ylabel('Actual Values')
plt.tight_layout()
plt.show()

"""# Interpretation:
The metrics measuring the performance of the Logistic Regression model with default settings show good performance. The model predicts the diagnosis with 97.4% precision and 93.9% accuracy. An AUC metric of 92.3% shows the model is performing well in distinguishing between malignant and benign cases. The F1-score demonstrates a good balance between precision and recall; however, the 86% recall means that 14% false negatives were made. As a health condition that may have fatal consequences, this would be a crucial metric to improve.

# Feature Selection and Hyperparameter Tuning
"""

# Following GeeksforGeeks. “How to Optimize Logistic Regression Performance.”

# Defining parameter grid for GridSearchCV to tune model performance.
param_grid = [
    {'penalty':['l1','l2','elasticnet','none'], # Penalty reduces the value of change to the coefficient to zero, near zero, or a combination during training.
    'C' : np.logspace(-4,4,20), # Inverse the instability by adding penalty that would favor stable solutions.
    'solver': ['lbfgs','newton-cg','liblinear','sag','saga'], # Already using liblinear for solver
    'max_iter'  : [100,1000,2500,5000] # Default is 100; however, increasing iteration of solver may improve performance. Will need to balance training time and model performance.
}
]

"""As this tool systematically reviews different combinations of hyperparameters and makes a recommendation for the logistic regression model; I would not be selecting the final hyperparametered set.

If I were to choose, I would choose the following parameters:

*   Elasticnet penalty to prevent overfitting from data noise and improve generalization to reduce false negatives.
*   Higher C (Inverse of Regularization) value to reduce the amount of regularization due. This is to trust the training data and relationships more.
*   The dataset is small and may not benefit from additional hyperparameter tuning.
"""

# Using GridSearchCV technique to find best hyperparameters to improve model performance.
clf = GridSearchCV(lr_model,param_grid = param_grid, cv = 3, verbose=True,n_jobs=-1)
clf

best_clf = clf.fit(x,y) # Training model with GridSearchCV with x and y.
best_clf.best_estimator_ # Displaying optimized model parameters.

# Running training and testing with hypertuned Logistic Regression model using GridSearchCV
lr2 = LogisticRegression(C=np.float64(1438.44988828766), random_state=42) # Including output from previous code.
lr2.fit(X_train, y_train) # Training the lr2 model
y_pred_lr2 = lr2.predict(X_test) # Making predictions on the lr2 test set

# Printing performance metrics for comparison
print('Hypertuned Logistic Regression Model Performance:')
print('Precision:', precision_score(y_test, y_pred_lr2))
print('Accuracy:', accuracy_score(y_test, y_pred_lr2))
print('Recall:', recall_score(y_test, y_pred_lr2))
print('F1-Score:', f1_score(y_test, y_pred_lr2))
print('AUC', metrics.roc_auc_score(y_test, y_pred_lr2))
print('Confusion Matrix:', confusion_matrix(y_test, y_pred_lr2))

"""# Comparing Performance:"""

# Performance Metrics for Baseline Logistic Regression (lr_model)
precision_lr = precision_score(y_test, y_pred_lr)
accuracy_lr = accuracy_score(y_test, y_pred_lr)
recall_lr = recall_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
auc_lr = roc_auc_score(y_test, y_pred_lr)
cm_lr = confusion_matrix(y_test, y_pred_lr)

# Performance Metrics for Hypertuned Logistic Regression (lr2_model)
precision_lr2 = precision_score(y_test, y_pred_lr2)
accuracy_lr2 = accuracy_score(y_test, y_pred_lr2)
recall_lr2 = recall_score(y_test, y_pred_lr2)
f1_lr2 = f1_score(y_test, y_pred_lr2)
auc_lr2 = roc_auc_score(y_test, y_pred_lr2)
cm_lr2 = confusion_matrix(y_test, y_pred_lr2)

# Create a DataFrame for comparison
comparison_df = pd.DataFrame({ 'Metric': ['Precision', 'Accuracy', 'Recall', 'F1-Score', 'AUC', 'Confusion Matrix'],
    'Initial LR': [precision_lr, accuracy_lr, recall_lr, f1_lr, auc_lr, cm_lr.tolist()],
    'Hypertuned LR': [precision_lr2, accuracy_lr2, recall_lr2, f1_lr2, auc_lr2, cm_lr2.tolist()]})

print(comparison_df.to_markdown(index=False))

"""The performance of the hypertuned Logistic Regression Model showed improvement with its recall metric and reduced the total false negatives by 1. However, a trade-off in overall accuracy and precision is observed, with 3 additional false positives seen in the hypertuned model compared to the initial model. With the goal of capturing malignant diagnosis, recall should be prioritized as the key performance metric.

# Alternative Model - Random Forest Classification
The data presents multiple features to consider and non-linear relationships that Random Forest models can tackle. It may also provide feature importance and insights into underlying factors that may contribute to a diagnosis or predict one.
"""

# Random Forest Binary Classification
rf_model = RandomForestClassifier(random_state=42) # Fitting data to Random Forest model
rf_model.fit(X_train, y_train) # Training the model
y_pred_rf = rf_model.predict(X_test) # Making predictions on the test set

print('\nRandom Forest Model Performance:')
print('Precision:', precision_score(y_test, y_pred_rf))
print('Accuracy:', accuracy_score(y_test, y_pred_rf))
print('Recall:', recall_score(y_test, y_pred_rf))
print('F1-Score:', f1_score(y_test, y_pred_rf))
print('AUC', metrics.roc_auc_score(y_test, y_pred_rf))
print('Confusion Matrix:', confusion_matrix(y_test, y_pred_rf))

# Performance Metrics for Random Forest Model (rf_model)
precision_rf =precision_score(y_test, y_pred_rf)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
F1_rf = f1_score(y_test, y_pred_rf)
auc_rf = metrics.roc_auc_score(y_test, y_pred_rf)
cm_rf_ = confusion_matrix(y_test, y_pred_rf)

# Create a DataFrame for comparison
comparison_df = pd.DataFrame({ 'Metric': ['Precision', 'Accuracy', 'Recall', 'F1-Score', 'AUC', 'Confusion Matrix'],
                              'Initial LR': [precision_lr, accuracy_lr, recall_lr, f1_lr, auc_lr, cm_lr.tolist()],
                              'Hypertuned LR': [precision_lr2, accuracy_lr2, recall_lr2, f1_lr2, auc_lr2, cm_lr2.tolist()],
                               'Random Forest': [precision_rf, accuracy_rf, recall_rf, F1_rf, auc_rf, cm_rf_.tolist()],})

print(comparison_df.to_markdown(index=False))

"""The best performance achieved with a Random Forest Model with returned with a lower overall performance the the logistic regression model. The classification completed by the random forest model demonstrate similar metrics in it's recall and further hypertuning of the random forest could benificial to its performance to reduce false negatives. That being said, overall precision and accuracy needs to remain high to identifiy different classes in the data and is critical for medical classifcation task.

Given the smaller dataset, the default settings for the Logistic Regression model or the hypertuned parameters are observed tothe better at this point.

# Reference
Brownlee, Jason. “Tune Hyperparameters for Classification Machine Learning Algorithms.” Machine Learning Mastery, 12 Dec. 2019, machinelearningmastery.com/hyperparameters-for-classification-machine-learning-algorithms/.

GeeksforGeeks. “EDA Exploratory Data Analysis in Python.” GeeksforGeeks, 10 June 2018, www.geeksforgeeks.org/data-analysis/exploratory-data-analysis-in-python/.

GeeksforGeeks. “How to Optimize Logistic Regression Performance.” GeeksforGeeks, 22 May 2024, www.geeksforgeeks.org/machine-learning/how-to-optimize-logistic-regression-performance/.

‌Tech, Tpoint. “Logistic Regression in Machine Learning.” Www.tpointtech.com, Tpoint Tech, 17 Mar. 2025, www.tpointtech.com/logistic-regression-in-machine-learning.


Python Programmer. “Evaluation Metrics for Classification - Python Programmer - Medium.” Medium, Medium, 17 May 2023, medium.com/@mlmind/evaluation-metrics-for-classification-fc770511052d.

‌
‌
"""